### ISSUE TITLE
Implement Bubble sort in PHP

### ISSUE THREAD

**Issue by yasirunilan** [yasirunilan/Algorithms#5]
Implement the Bubble sort in PHP language while following the contributing guideline.

**Comment by ishitach** [comment]
Hi,
I have written the code for the same but getting this error while pushing:

remote: Repository not found.
fatal: repository 'https://github.com/ishitach/Algorithms.git/' not found

Could you please help, I am unable to push due to this. I have followed the steps given in README.

**Comment by yasirunilan** [comment]
@ishitach please check whether you have added the remote repository.

**Comment by yasirunilan** [comment]
closed with #26
