### ISSUE TITLE
Implement Quick sort in C++

### ISSUE THREAD

**Issue by yasirunilan** [yasirunilan/Algorithms#9]
Implement the Quick sort in C++ language while following the contributing guideline.

**Comment by Anirudh257** [comment]
Hey, I can work on this

**Comment by VibhorCodecianGupta** [comment]
Hello, I have a nice and clean code snippet ready for this algo. Would like to work on this

**Comment by yasirunilan** [comment]
@VibhorCodecianGupta @Anirudh257 please proceed.
